# Generated by Django 4.0.5 on 2022-11-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_remove_category_types_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_types',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
