# Generated by Django 4.0.5 on 2022-11-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_remove_order_product_order_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='coupon_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('valid_date', models.DateField()),
                ('discount', models.IntegerField(null=True)),
            ],
        ),
    ]
