# Generated by Django 4.0.5 on 2022-11-07 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_coupon_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
