# Generated by Django 4.0.5 on 2022-11-08 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0001_initial'),
        ('products', '0003_product_description'),
        ('cart', '0014_cart_delete_order_alter_orderinfo_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='State',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='items',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='mob_no',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='pincode',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.customer'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='ordered_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
